DROP FUNCTION set_norme(TEXT);
DROP FUNCTION get_norme();
DROP FUNCTION set_quantifier(TEXT);
DROP FUNCTION get_quantifier();
DROP FUNCTION set_mu(FLOAT) CASCADE;
DROP FUNCTION get_mu() CASCADE;
DROP FUNCTION set_k(INTEGER);
DROP FUNCTION get_k();
DROP FUNCTION get_alpha();
DROP FUNCTION set_alpha(FLOAT);

DROP FUNCTION float2fuzzy(REAL) CASCADE;
DROP FUNCTION float2fuzzy(NUMERIC) CASCADE;
DROP FUNCTION bool2fuzzy(BOOLEAN) CASCADE;
DROP FUNCTION fuzzy2bool(FLOAT) CASCADE;
DROP FUNCTION fuzzy2bool(REAL) CASCADE;

DROP FUNCTION trapezoidalfuzzypredicate(REAL, REAL, REAL, REAL, REAL);
DROP FUNCTION trapezoidal_fuzzy_predicate(FLOAT, FLOAT, FLOAT, FLOAT, FLOAT);

DROP FUNCTION ISf(NUMERIC, VARCHAR) CASCADE;
DROP FUNCTION ISf(VARCHAR, VARCHAR) CASCADE;
DROP FUNCTIOn create_predicate(TEXT, FLOAT, FLOAT, FLOAT, FLOAT);
DROP FUNCTION create_restricted_predicate(TEXT, TEXT, FLOAT, FLOAT, FLOAT, FLOAT);
DROP FUNCTION create_categorial_predicate(TEXT, TEXT);

DROP FUNCTION fuzzy_or_operator(FLOAT, FLOAT) CASCADE;
DROP FUNCTION fuzzy_and_operator(FLOAT, FLOAT) CASCADE;
DROP FUNCTION fuzzy_not_operator(FLOAT) CASCADE;

DROP FUNCTION most_of(FLOAT);

DROP FUNCTION la_plupart(VARIADIC FLOAT[]);

DROP FUNCTION zadeh(VARIADIC xs FLOAT[]);
DROP FUNCTION cta(VARIADIC xs FLOAT[]);
DROP FUNCTION owa(VARIADIC FLOAT[]);
DROP FUNCTION arith_mean(VARIADIC FLOAT[]);

DROP FUNCTION closeness(a FLOAT, b FLOAT) CASCADE;
DROP FUNCTION mu_in(anynonarray, anyarray) CASCADE;
DROP FUNCTION mu_in_f(anynonarray, anyarray) CASCADE;
